=== TheCell/XMLWebsite/DBs/coursesDB.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="courses" type="courses">
        <xs:unique name="item_unique">
            <xs:selector xpath="item"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="courses">
        <xs:sequence>
            <xs:element ref="course" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="course">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="dateFrom" type="xs:date"/>
                <xs:element name="dateTo" type="xs:date"/>
                <xs:element name="reoccurrance" type="occurance"/>
                <xs:element name="timeFrom" type="xs:time"/>
                <xs:element name="timeTo" type="xs:time"/>
                <xs:element name="level" type="xs:string">
                <!--todo: @simon enum fÃ¼r level (evtl. recommended too)-->
                </xs:element>
                <xs:element name="state" type="stateType"/>
                <xs:element name="maxParticipants" type="xs:int"/>
                <xs:element name="recommendedFor" type="xs:string"/>
                <xs:element name="language" type="lang"/>
                <xs:element ref="courseReservationIDs"/>
                <xs:element name="description" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="courseID" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="courseReservationIDs">
        <xs:complexType>
            <xs:sequence >
                <xs:element name="reservationID" type="resID" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="occurance">
        <xs:restriction base="xs:string">
            <xs:enumeration value="once"/>
            <xs:enumeration value="daily"/>
            <xs:enumeration value="weekly"/>
            <xs:enumeration value="monthly"/>
            <xs:enumeration value="annual"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="stateType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="active"/>
            <xs:enumeration value="inactive"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="lang">
        <xs:restriction base="xs:string">
            <xs:enumeration value="German"/>
            <xs:enumeration value="English"/>
            <!--More following?-->
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="courseID">
        <xs:restriction base="xs:string">
            <xs:length value="4"/>
            <xs:pattern value="[C]\d{3}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="resID">
        <xs:restriction base="xs:string">
            <xs:length value="6"/>
            <xs:pattern value="(RES)\d{3}"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== TheCell/XMLWebsite/DBs/coursesDB.xml
<?xml version="1.0" encoding="UTF-8"?>
<courses xsi:noNamespaceSchemaLocation="coursesDB.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <course id="C001">
        <name>Bouldern</name>
        <dateFrom>2018-04-05</dateFrom>
        <dateTo>2018-04-05</dateTo>
        <reoccurrance>einmalig</reoccurrance>
        <timeFrom>10:00:00</timeFrom>
        <timeTo>13:00:00</timeTo>
        <level>Fortgeschrittene</level>
        <state>aktiv</state>
        <maxParticipants>10</maxParticipants>
        <recommendedFor>Alle</recommendedFor>
        <language>Deutsch</language>
        <courseReservationIDs/>
        <description>Gemeinsames Bouldern</description>
    </course>
    <course id="C002">
        <name>Klettern</name>
        <dateFrom>2018-04-05</dateFrom>
        <dateTo>2018-04-05</dateTo>
        <reoccurrance>einmalig</reoccurrance>
        <timeFrom>17:00:00</timeFrom>
        <timeTo>21:00:00</timeTo>
        <level>Anfänger</level>
        <state>aktiv</state>
        <maxParticipants>10</maxParticipants>
        <recommendedFor>Normal, Amputation</recommendedFor>
        <language>Deutsch</language>
        <courseReservationIDs/>
        <description>Klettern als Gruppe</description>
    </course>
    <course id="C003">
        <name>Klettern</name>
        <dateFrom>2018-04-07</dateFrom>
        <dateTo>2018-04-07</dateTo>
        <reoccurrance>einmalig</reoccurrance>
        <timeFrom>17:00:00</timeFrom>
        <timeTo>21:00:00</timeTo>
        <level>Profi</level>
        <state>aktiv</state>
        <maxParticipants>10</maxParticipants>
        <recommendedFor>Normal, Geistig eingeschränkt</recommendedFor>
        <language>Deutsch</language>
        <courseReservationIDs/>
        <description>Klettertraining</description>
    </course>
    <course id="C004">
        <name>Klettern</name>
        <dateFrom>2018-04-07</dateFrom>
        <dateTo>2018-04-07</dateTo>
        <reoccurrance>einmalig</reoccurrance>
        <timeFrom>17:00:00</timeFrom>
        <timeTo>21:00:00</timeTo>
        <level>Anfänger</level>
        <state>aktiv</state>
        <maxParticipants>20</maxParticipants>
        <recommendedFor>Normal, Geistig eingeschränkt, Amputation</recommendedFor>
        <language>Deutsch</language>
        <courseReservationIDs/>
        <description>Kletterplausch</description>
    </course>
    <course id="C005">
        <name>Bouldern</name>
        <dateFrom>2018-04-15</dateFrom>
        <dateTo>2018-04-15</dateTo>
        <reoccurrance>einmalig</reoccurrance>
        <timeFrom>17:00:00</timeFrom>
        <timeTo>21:00:00</timeTo>
        <level>Fortgeschrittene</level>
        <state>aktiv</state>
        <maxParticipants>20</maxParticipants>
        <recommendedFor>Normal, Geistig eingeschränkt, Amputation</recommendedFor>
        <language>Deutsch</language>
        <courseReservationIDs/>
        <description>Bouldern als Gruppe</description>
    </course>
    <course id="C006">
        <name>Klettern</name>
        <dateFrom>2018-03-07</dateFrom>
        <dateTo>2018-03-07</dateTo>
        <reoccurrance>einmalig</reoccurrance>
        <timeFrom>13:00:00</timeFrom>
        <timeTo>16:00:00</timeTo>
        <level>Anfänger</level>
        <state>aktiv</state>
        <maxParticipants>20</maxParticipants>
        <recommendedFor>Normal, Geistig eingeschränkt, Amputation</recommendedFor>
        <language>Deutsch</language>
        <courseReservationIDs/>
        <description>Kletterplausch</description>
    </course>
    <course id="C007">
        <name>Bouldern</name>
        <dateFrom>2018-03-08</dateFrom>
        <dateTo>2018-03-08</dateTo>
        <reoccurrance>einmalig</reoccurrance>
        <timeFrom>08:00:00</timeFrom>
        <timeTo>11:00:00</timeTo>
        <level>Fortgeschrittene</level>
        <state>aktiv</state>
        <maxParticipants>20</maxParticipants>
        <recommendedFor>Normal, Geistig eingeschränkt, Amputation</recommendedFor>
        <language>Deutsch</language>
        <courseReservationIDs/>
        <description>Bouldern als Gruppe</description>
    </course>
    <course id="C008">
        <name>Bouldern</name>
        <dateFrom>2018-03-10</dateFrom>
        <dateTo>2018-03-10</dateTo>
        <reoccurrance>einmalig</reoccurrance>
        <timeFrom>10:00:00</timeFrom>
        <timeTo>13:00:00</timeTo>
        <level>Fortgeschrittene</level>
        <state>aktiv</state>
        <maxParticipants>10</maxParticipants>
        <recommendedFor>Alle</recommendedFor>
        <language>Deutsch</language>
        <courseReservationIDs/>
        <description>Gemeinsames Bouldern</description>
    </course>
    <course id="C009">
        <name>Bouldern</name>
        <dateFrom>2018-03-14</dateFrom>
        <dateTo>2018-03-14</dateTo>
        <reoccurrance>einmalig</reoccurrance>
        <timeFrom>10:00:00</timeFrom>
        <timeTo>13:00:00</timeTo>
        <level>Fortgeschrittene</level>
        <state>aktiv</state>
        <maxParticipants>10</maxParticipants>
        <recommendedFor>Normal, Geistig eingeschränkt, Amputation</recommendedFor>
        <language>Deutsch</language>
        <courseReservationIDs/>
        <description>Gemeinsames Bouldern</description>
    </course>
    <course id="C010">
        <name>Bouldern</name>
        <dateFrom>2018-03-17</dateFrom>
        <dateTo>2018-03-17</dateTo>
        <reoccurrance>einmalig</reoccurrance>
        <timeFrom>10:00:00</timeFrom>
        <timeTo>13:00:00</timeTo>
        <level>Fortgeschrittene</level>
        <state>aktiv</state>
        <maxParticipants>10</maxParticipants>
        <recommendedFor>Alle</recommendedFor>
        <language>Deutsch</language>
        <courseReservationIDs/>
        <description>Gemeinsames Bouldern</description>
    </course>
    <course id="C011">
        <name>Bouldern</name>
        <dateFrom>2018-03-21</dateFrom>
        <dateTo>2018-03-21</dateTo>
        <reoccurrance>einmalig</reoccurrance>
        <timeFrom>10:00:00</timeFrom>
        <timeTo>13:00:00</timeTo>
        <level>Fortgeschrittene</level>
        <state>aktiv</state>
        <maxParticipants>10</maxParticipants>
        <recommendedFor>Normal, Geistig eingeschränkt, Amputation</recommendedFor>
        <language>Deutsch</language>
        <courseReservationIDs/>
        <description>Gemeinsames Bouldern</description>
    </course>
    <course id="C012">
        <name>Bouldern</name>
        <dateFrom>2018-03-25</dateFrom>
        <dateTo>2018-03-25</dateTo>
        <reoccurrance>einmalig</reoccurrance>
        <timeFrom>10:00:00</timeFrom>
        <timeTo>13:00:00</timeTo>
        <level>Fortgeschrittene</level>
        <state>aktiv</state>
        <maxParticipants>10</maxParticipants>
        <recommendedFor>Alle</recommendedFor>
        <language>Deutsch</language>
        <courseReservationIDs/>
        <description>Gemeinsames Bouldern</description>
    </course>
    <course id="C013">
        <name>Bouldern</name>
        <dateFrom>2018-03-29</dateFrom>
        <dateTo>2018-03-29</dateTo>
        <reoccurrance>einmalig</reoccurrance>
        <timeFrom>10:00:00</timeFrom>
        <timeTo>13:00:00</timeTo>
        <level>Fortgeschrittene</level>
        <state>aktiv</state>
        <maxParticipants>10</maxParticipants>
        <recommendedFor>Normal, Geistig eingeschränkt, Amputation</recommendedFor>
        <language>Deutsch</language>
        <courseReservationIDs/>
        <description>Gemeinsames Bouldern</description>
    </course>
    <course id="C014">
        <name>Bouldern</name>
        <dateFrom>2018-04-03</dateFrom>
        <dateTo>2018-04-03</dateTo>
        <reoccurrance>einmalig</reoccurrance>
        <timeFrom>10:00:00</timeFrom>
        <timeTo>13:00:00</timeTo>
        <level>Fortgeschrittene</level>
        <state>aktiv</state>
        <maxParticipants>10</maxParticipants>
        <recommendedFor>Alle</recommendedFor>
        <language>Deutsch</language>
        <courseReservationIDs/>
        <description>Gemeinsames Bouldern</description>
    </course>
    <course id="C015">
        <name>Klettern</name>
        <dateFrom>2018-03-15</dateFrom>
        <dateTo>2018-03-15</dateTo>
        <reoccurrance>einmalig</reoccurrance>
        <timeFrom>17:00:00</timeFrom>
        <timeTo>21:00:00</timeTo>
        <level>Anfänger</level>
        <state>aktiv</state>
        <maxParticipants>10</maxParticipants>
        <recommendedFor>Normal, Amputation</recommendedFor>
        <language>Deutsch</language>
        <courseReservationIDs/>
        <description>Klettern als Gruppe</description>
    </course>
    <course id="C030">
        <name>Klettern</name>
        <dateFrom>2018-03-15</dateFrom>
        <dateTo>2018-03-15</dateTo>
        <reoccurrance>einmalig</reoccurrance>
        <timeFrom>17:00:00</timeFrom>
        <timeTo>21:00:00</timeTo>
        <level>Anfänger</level>
        <state>aktiv</state>
        <maxParticipants>10</maxParticipants>
        <recommendedFor>Normal</recommendedFor>
        <language>Deutsch</language>
        <courseReservationIDs/>
        <description>Klettern als Gruppe</description>
    </course>
    <course id="C016">
        <name>Klettern</name>
        <dateFrom>2018-03-20</dateFrom>
        <dateTo>2018-03-20</dateTo>
        <reoccurrance>einmalig</reoccurrance>
        <timeFrom>17:00:00</timeFrom>
        <timeTo>21:00:00</timeTo>
        <level>Anfänger</level>
        <state>aktiv</state>
        <maxParticipants>10</maxParticipants>
        <recommendedFor>Normal, Amputation</recommendedFor>
        <language>Deutsch</language>
        <courseReservationIDs/>
        <description>Klettern als Gruppe</description>
    </course>
    <course id="C017">
        <name>Klettern</name>
        <dateFrom>2018-03-24</dateFrom>
        <dateTo>2018-03-24</dateTo>
        <reoccurrance>einmalig</reoccurrance>
        <timeFrom>17:00:00</timeFrom>
        <timeTo>21:00:00</timeTo>
        <level>Anfänger</level>
