=== TheCell/XMLWebsite/DBs/equipmentDB.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

            <xs:element name="equipment" type="equip">
                <xs:unique name="item_unique">
                    <xs:selector xpath="item"/>
                    <xs:field xpath="@id"/>
                </xs:unique>
            </xs:element>

    <xs:complexType name="equip">
        <xs:sequence>
            <xs:element ref="item" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="item">
        <xs:complexType>
                <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="roomID" type="roomID"/>
                    <xs:element name="description" type="xs:string"/>
                </xs:sequence>
            <xs:attribute name="id" type="itemID" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="itemID">
        <xs:restriction base="xs:string">
            <xs:length value="4"/>
            <xs:pattern value="[E]\d{3}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="roomID">
        <xs:restriction base="xs:string">
            <xs:length value="4"/>
            <xs:pattern value="[R]\d{3}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== TheCell/XMLWebsite/DBs/equipmentDB.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2013 sp1 (http://www.altova.com)-->
<equipment xsi:noNamespaceSchemaLocation="equipmentDB.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <item id="E001">
        <name>Schwimmnoodle</name>
        <roomID>R022</roomID>
        <description>Schwimmunterstützung</description>
    </item>
    <item id="E002">
        <name>Schwimmgürtel</name>
        <roomID>R022</roomID>
        <description>Schwimmunterstützung</description>
    </item>
    <item id="E003">
        <name>Aqua-Jogging Gürtel</name>
        <roomID>R022</roomID>
        <description>Schwimmunterstützung für Wassersport</description>
    </item>
    <item id="E004">
        <name>Schwimmlernhilfe</name>
        <roomID>R022</roomID>
        <description>Schwimmunterstützung</description>
    </item>
    <item id="E005">
        <name>Schwimmbrett</name>
        <roomID>R022</roomID>
        <description>Schwimmunterstützung</description>
    </item>
    <item id="E006">
        <name>Aquarider</name>
        <roomID>R022</roomID>
        <description>Wasserfahrrad für Wassersport</description>
    </item>
    <item id="E007">
        <name>Beinschwimmer</name>
        <roomID>R022</roomID>
        <description>Schwimmunterstützung für Wassersport</description>
    </item>
    <item id="E008">
        <name>Schwimmflossen</name>
        <roomID>R022</roomID>
        <description>Schwimmunterstützung für Wassersport</description>
    </item>
    <item id="E009">
        <name>Tauchreifen</name>
        <roomID>R022</roomID>
        <description>Bögen zum durchtauchen für Tauchübungen. Abstecken für Tauchstrecken.</description>
    </item>
    <item id="E010">
        <name>Tauchring</name>
        <roomID>R022</roomID>
        <description>Ringgewichte für Tauchübungen</description>
    </item>
    <item id="E011">
        <name>Handpaddel</name>
        <roomID>R022</roomID>
        <description>Schwimmunterstützung</description>
    </item>
    <item id="E012">
        <name>Aqua-Stepp</name>
        <roomID>R022</roomID>
        <description>Trittschemmel für Steppübungen im Wasser.</description>
    </item>
    <item id="E013">
        <name>Wasserballtor</name>
        <roomID>R022</roomID>
        <description>Wassertor für Ballsport im Wasser.</description>
    </item>
    <item id="E014">
        <name>Schwimmergometer</name>
        <roomID>R022</roomID>
        <description>Fitnessgerät für Schwimmstilübungen.</description>
    </item>
    <item id="E015">
        <name>Unterqwassertrampolin</name>
        <roomID>R022</roomID>
        <description>Fitnessgerät für Wassersport.</description>
    </item>
    <item id="E016">
        <name>Slalom-Tauchspiel</name>
        <roomID>R022</roomID>
        <description>Luftröhren mit Saugnapf für Tauchsport.</description>
    </item>
    <item id="E017">
        <name>Rollstuhlkran</name>
        <roomID>R022</roomID>
        <description>Ein und Ausstiegshilfe ins Schwimmbecken.</description>
    </item>
</equipment>
