=== TheCell/XMLWebsite/DBs/reservationsDB.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="reservations" type="reservs">
        <xs:unique name="item_unique">
            <xs:selector xpath="item"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="reservs">
        <xs:sequence>
            <xs:element ref="reservation" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="reservation">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="dateFrom" type="xs:date"/>
                <xs:element name="dateTo" type="xs:date"/>
                <xs:element name="timeFrom" type="xs:time"/>
                <xs:element name="timeTo" type="xs:time"/>
                <xs:element name="note" type="xs:string"/>
                <xs:element name="user" type="userID"/>
                <xs:element name="entityID" type="entityID"/>
            </xs:sequence>
            <xs:attribute name="id" type="resID" use="required"/>
        </xs:complexType>
    </xs:element>


    <xs:simpleType name="entityID">
        <xs:restriction base="xs:string">
            <xs:length value="4"/>
            <xs:pattern value="[ER]\d{3}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="resID">
        <xs:restriction base="xs:string">
            <xs:length value="6"/>
            <xs:pattern value="(RES)\d{3}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="userID">
        <xs:restriction base="xs:string">
            <xs:length value="4"/>
            <xs:pattern value="[U]\d{3}"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== TheCell/XMLWebsite/DBs/reservationsDB.xml
<?xml version="1.0" encoding="UTF-8"?>
<reservations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="reservationsDB.xsd">
    <reservation>
        <username/>
        <dateFrom>2018-01-23</dateFrom>
        <dateTo>2018-02-12</dateTo>
        <timeFrom>13:50:00</timeFrom>
        <timeTo>14:50:00</timeTo>
        <note/>
        <entityID>R002</entityID>
    </reservation>
    <reservation>
        <username/>
        <dateFrom>2018-11-23</dateFrom>
        <dateTo>2018-11-30</dateTo>
        <timeFrom>09:00:00</timeFrom>
        <timeTo>12:00:00</timeTo>
        <note/>
        <entityID>E034</entityID>
    </reservation>
    <reservation>
        <username>Peter</username>
        <dateFrom>2018-03-11</dateFrom>
        <dateTo>2018-03-11</dateTo>
        <timeFrom>00:00:00</timeFrom>
        <timeTo>00:02:00</timeTo>
        <note>qwer</note>
        <entityID>E001</entityID>
    </reservation>
    <reservation>
        <username>Peter</username>
        <dateFrom>2018-03-11</dateFrom>
        <dateTo>2018-03-11</dateTo>
        <timeFrom>00:00:00</timeFrom>
        <timeTo>00:02:00</timeTo>
        <note>asdf</note>
        <entityID>E001</entityID>
    </reservation>
    <reservation>
        <username>Peter</username>
        <dateFrom>2018-03-11</dateFrom>
        <dateTo>2018-03-11</dateTo>
        <timeFrom>00:00:00</timeFrom>
        <timeTo>00:02:00</timeTo>
        <note>asdf</note>
        <entityID>E001</entityID>
    </reservation>
    <reservation>
        <username>Peter</username>
        <dateFrom>2018-03-11</dateFrom>
        <dateTo>2018-03-11</dateTo>
        <timeFrom>00:00:00</timeFrom>
        <timeTo>00:02:00</timeTo>
        <note>asdf1</note>
        <entityID>E001</entityID>
    </reservation>
<reservation><username>Peter</username><dateFrom>2018-03-11</dateFrom><dateTo>2018-03-11</dateTo><timeFrom>00:00:00</timeFrom><timeTo>00:02:00</timeTo><note>asdf</note><entityID>E001</entityID></reservation></reservations>
